import { NextResponse } from 'next/server';

export async function GET() {
  const products = [
    {
      id: '1',
      name: 'Vanilla Bean Delight',
      price: 5.0,
      rating: 4.8,
      image: '/public/vanilla_bean_delight.jpg',
      description: 'A timeless classic made with the finest vanilla beans for a rich, creamy experience.',
      ingredients: ['Cream', 'Sugar', 'Vanilla Beans', 'Egg Yolks'],
      category: 'Classic',
    },
    {
      id: '2',
      name: 'Chocolate Fudge Swirl',
      price: 5.0,
      rating: 4.7,
      image: '/public/chocolate_fudge_swirl.jpg',
      description: 'Decadent chocolate ice cream with a luscious fudge swirl.',
      ingredients: ['Cream', 'Sugar', 'Cocoa', 'Fudge Sauce', 'Egg Yolks'],
      category: 'Classic',
    },
    {
      id: '3',
      name: 'Strawberry Sensation',
      price: 5.0,
      rating: 4.6,
      image: '/public/strawberry_sensation.jpg',
      description: 'Creamy and delicious with real strawberry pieces for a fruity burst.',
      ingredients: ['Cream', 'Sugar', 'Strawberries', 'Egg Yolks'],
      category: 'Classic',
    },
    {
      id: '4',
      name: 'Mint Chocolate Chip',
      price: 5.0,
      rating: 4.5,
      image: '/public/mint_chocolate_chip.jpg',
      description: 'Refreshing mint ice cream loaded with dark chocolate chips.',
      ingredients: ['Cream', 'Sugar', 'Mint Extract', 'Dark Chocolate Chips', 'Egg Yolks'],
      category: 'Classic',
    },
    {
      id: '5',
      name: 'Cookies and Cream',
      price: 5.0,
      rating: 4.8,
      image: '/public/cookies_and_cream.jpg',
      description: 'Creamy vanilla ice cream mixed with crunchy cookie pieces.',
      ingredients: ['Cream', 'Sugar', 'Vanilla Extract', 'Chocolate Cookies', 'Egg Yolks'],
      category: 'Classic',
    },
    {
      id: '6',
      name: 'Butter Pecan',
      price: 5.0,
      rating: 4.6,
      image: '/public/butter_pecan.jpg',
      description: 'Rich and creamy ice cream with roasted pecan pieces.',
      ingredients: ['Cream', 'Sugar', 'Pecans', 'Butter', 'Egg Yolks'],
      category: 'Classic',
    },
    {
      id: '7',
      name: 'Rocky Road',
      price: 5.0,
      rating: 4.7,
      image: '/public/rocky_road.jpg',
      description: 'Chocolate ice cream with marshmallows and almonds.',
      ingredients: ['Cream', 'Sugar', 'Cocoa', 'Marshmallows', 'Almonds', 'Egg Yolks'],
      category: 'Classic',
    },
    {
      id: '8',
      name: 'Classic Coffee',
      price: 5.0,
      rating: 4.5,
      image: '/public/classic_coffee.jpg',
      description: 'Rich and aromatic coffee-flavored ice cream.',
      ingredients: ['Cream', 'Sugar', 'Coffee Extract', 'Egg Yolks'],
      category: 'Classic',
    },
    {
      id: '9',
      name: 'Pumpkin Spice',
      price: 5.0,
      rating: 4.7,
      image: '/public/pumpkin_spice.jpg',
      description: 'Celebrate the fall season with this warm, spiced pumpkin ice cream.',
      ingredients: ['Cream', 'Sugar', 'Pumpkin Puree', 'Cinnamon', 'Nutmeg', 'Egg Yolks'],
      category: 'Seasonal',
    },
    {
      id: '10',
      name: 'Eggnog Delight',
      price: 5.0,
      rating: 4.8,
      image: '/public/eggnog_delight.jpg',
      description: 'Rich and creamy eggnog-flavored ice cream for the winter holidays.',
      ingredients: ['Cream', 'Sugar', 'Eggnog', 'Nutmeg', 'Egg Yolks'],
      category: 'Seasonal',
    },
    {
      id: '34',
      name: 'Peppermint Candy Cane',
      price: 5.0,
      rating: 4.6,
      image: '/public/peppermint_candy_cane.jpg',
      description: 'A festive holiday treat with peppermint ice cream and candy cane pieces.',
      ingredients: ['Cream', 'Sugar', 'Peppermint Extract', 'Candy Cane Pieces', 'Egg Yolks'],
      category: 'Seasonal',
    },
    {
      id: '11',
      name: 'Spring Berry Medley',
      price: 5.0,
      rating: 4.7,
      image: '/public/spring_berry_medley.jpg',
      description: 'A mix of refreshing berries for a delightful spring treat.',
      ingredients: ['Cream', 'Sugar', 'Mixed Berries', 'Egg Yolks'],
      category: 'Seasonal',
    },
    {
      id: '12',
      name: 'Summer Citrus',
      price: 5.0,
      rating: 4.6,
      image: '/public/summer_citrus.jpg',
      description: 'A tangy and refreshing citrus blend perfect for summer.',
      ingredients: ['Cream', 'Sugar', 'Citrus Extract', 'Lemon Zest', 'Egg Yolks'],
      category: 'Seasonal',
    },
    {
      id: '13',
      name: 'Maple Walnut',
      price: 5.0,
      rating: 4.8,
      image: '/public/maple_walnut.jpg',
      description: 'A rich and nutty flavor with a hint of maple syrup.',
      ingredients: ['Cream', 'Sugar', 'Maple Syrup', 'Walnuts', 'Egg Yolks'],
      category: 'Seasonal',
    },
    {
      id: '14',
      name: 'Coconut Paradise',
      price: 5.0,
      rating: 4.8,
      image: '/public/coconut_paradise.jpg',
      description: 'Creamy coconut-based ice cream with a tropical coconut flavor.',
      ingredients: ['Coconut Milk', 'Coconut Cream', 'Cane Sugar', 'Vanilla Extract'],
      category: 'Vegan',
    },
    {
      id: '15',
      name: 'Chocolate Almond',
      price: 5.0,
      rating: 4.7,
      image: '/public/chocolate_almond.jpg',
      description: 'Rich and creamy chocolate ice cream with almond pieces.',
      ingredients: ['Almond Milk', 'Cocoa', 'Cane Sugar', 'Almond Pieces'],
      category: 'Vegan',
    },
    {
      id: '16',
      name: 'Mango Sorbet',
      price: 5.0,
      rating: 4.6,
      image: '/public/mango_sorbet.jpg',
      description: 'Refreshing and fruity mango sorbet made with real mangoes.',
      ingredients: ['Mango Puree', 'Cane Sugar', 'Water'],
      category: 'Vegan',
    },
    {
      id: '17',
      name: 'Blueberry Acai',
      price: 5.0,
      rating: 4.7,
      image: '/public/blueberry_acai.jpg',
      description: 'A refreshing sorbet with the antioxidant benefits of blueberries and acai berries.',
      ingredients: ['Blueberry Puree', 'Acai Berry Puree', 'Cane Sugar', 'Water'],
      category: 'Vegan',
    },
    {
      id: '18',
      name: 'Pistachio Dream (made with almond milk)',
      price: 5.0,
      rating: 4.6,
      image: '/public/pistachio_dream.jpg',
      description: 'Lovely pistachio flavor made creamy with almond milk.',
      ingredients: ['Almond Milk', 'Cane Sugar', 'Pistachios'],
      category: 'Vegan',
    },
    {
      id: '19',
      name: 'Vegan Vanilla',
      price: 5.0,
      rating: 4.5,
      image: '/public/vegan_vanilla.jpg',
      description: 'A vegan take on the classic vanilla flavor made with almond milk.',
      ingredients: ['Almond Milk', 'Vanilla Extract', 'Cane Sugar'],
      category: 'Vegan',
    },
    {
      id: '20',
      name: 'Raspberry Ripple Sorbet',
      price: 5.0,
      rating: 4.7,
      image: '/public/raspberry_ripple_sorbet.jpg',
      description: 'Tangy raspberry sorbet swirled with rich raspberry sauce.',
      ingredients: ['Raspberry Puree', 'Cane Sugar', 'Water'],
      category: 'Vegan',
    },
    {
      id: '21',
      name: 'Salted Caramel Pretzel',
      price: 5.0,
      rating: 4.8,
      image: '/public/salted_caramel_pretzel.jpg',
      description: 'Creamy caramel ice cream with salted caramel swirls and crunchy pretzel pieces.',
      ingredients: ['Cream', 'Sugar', 'Caramel Sauce', 'Pretzels', 'Sea Salt', 'Egg Yolks'],
      category: 'Limited Edition',
    },
    {
      id: '22',
      name: 'Lavender Honey',
      price: 5.0,
      rating: 4.7,
      image: '/public/lavender_honey.jpg',
      description: 'A floral and sweet treat made with real lavender and honey.',
      ingredients: ['Cream', 'Sugar', 'Lavender', 'Honey', 'Egg Yolks'],
      category: 'Limited Edition',
    },
    {
      id: '23',
      name: 'Cherry Bourbon',
      price: 5.0,
      rating: 4.8,
      image: '/public/cherry_bourbon.jpg',
      description: 'Luxurious cherry ice cream with a hint of bourbon.',
      ingredients: ['Cream', 'Sugar', 'Cherries', 'Bourbon', 'Egg Yolks'],
      category: 'Limited Edition',
    },
    {
      id: '24',
      name: 'Rose Pistachio',
      price: 5.0,
      rating: 4.6,
      image: '/public/rose_pistachio.jpg',
      description: 'Unique and delightful with the delicate flavor of rose and crunchy pistachio.',
      ingredients: ['Cream', 'Sugar', 'Rosewater', 'Pistachios', 'Egg Yolks'],
      category: 'Limited Edition',
    },
    {
      id: '25',
      name: 'Matcha Green Tea',
      price: 5.0,
      rating: 4.7,
      image: '/public/matcha_green_tea.jpg',
      description: 'Vibrant and earthy flavor made with real matcha green tea.',
      ingredients: ['Cream', 'Sugar', 'Matcha Powder', 'Egg Yolks'],
      category: 'Limited Edition',
    },
    {
      id: '26',
      name: 'Black Sesame Delight',
      price: 5.0,
      rating: 4.6,
      image: '/public/black_sesame_delight.jpg',
      description: 'A unique treat with the rich, nutty flavor of black sesame.',
      ingredients: ['Cream', 'Sugar', 'Black Sesame Seeds', 'Egg Yolks'],
      category: 'Limited Edition',
    },
    {
      id: '27',
      name: 'Spicy Chocolate Hazelnut',
      price: 5.0,
      rating: 4.7,
      image: '/public/spicy_chocolate_hazelnut.jpg',
      description: 'A bold combination of chocolate, hazelnut, and a hint of spice.',
      ingredients: ['Cream', 'Sugar', 'Cocoa', 'Hazelnuts', 'Chili Pepper', 'Egg Yolks'],
      category: 'Limited Edition',
    },
    {
      id: '28',
      name: 'Sugar-Free Vanilla',
      price: 5.0,
      rating: 4.6,
      image: '/public/sugar_free_vanilla.jpg',
      description: 'The classic vanilla taste with no added sugar.',
      ingredients: ['Cream', 'Vanilla Extract', 'Sugar Substitute (Erythritol, Stevia)', 'Egg Yolks'],
      category: 'Special Dietary Options',
    },
    {
      id: '29',
      name: 'Low-Fat Chocolate',
      price: 5.0,
      rating: 4.5,
      image: '/public/low_fat_chocolate.jpg',
      description: 'Creamy chocolate ice cream with reduced fat.',
      ingredients: ['Low-Fat Milk', 'Cocoa', 'Sugar', 'Egg Yolks'],
      category: 'Special Dietary Options',
    },
    {
      id: '30',
      name: 'Keto-Friendly Coffee',
      price: 5.0,
      rating: 4.6,
      image: '/public/keto_friendly_coffee.jpg',
      description: 'Rich coffee ice cream with keto-friendly ingredients.',
      ingredients: ['Cream', 'Coffee Extract', 'Sugar Substitute (Erythritol, Stevia)', 'Egg Yolks'],
      category: 'Special Dietary Options',
    },
    {
      id: '31',
      name: 'Gluten-Free Brownie Batter',
      price: 5.0,
      rating: 4.7,
      image: '/public/gluten_free_brownie_batter.jpg',
      description: "Delicious brownie batter ice cream that's gluten-free.",
      ingredients: ['Cream', 'Sugar', 'Cocoa', 'Gluten-Free Brownie Pieces', 'Egg Yolks'],
      category: 'Special Dietary Options',
    },
    {
      id: '32',
      name: 'Dairy-Free Dark Chocolate',
      price: 5.0,
      rating: 4.8,
      image: '/public/dairy_free_dark_chocolate.jpg',
      description: 'Rich and creamy dark chocolate without any dairy.',
      ingredients: ['Coconut Milk', 'Cocoa', 'Cane Sugar'],
      category: 'Special Dietary Options',
    },
    {
      id: '33',
      name: 'Protein-Packed Peanut Butter',
      price: 5.0,
      rating: 4.6,
      image: '/public/protein_packed_peanut_butter.jpg',
      description: 'Creamy peanut butter ice cream with extra protein.',
      ingredients: ['Cream', 'Sugar', 'Peanut Butter', 'Whey Protein'],
      category: 'Special Dietary Options',
    },
  ];
  return NextResponse.json(products);
}
